name: Linting
run-name: "Linting run by @${{ github.actor }}, event: ${{ github.event_name }}"
on:
  workflow_call:
concurrency:
  group: linting-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      - name: Install Dependencies
        run: npm ci
      - name: Linting
        run: npx eslint .
